// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjgxeexnyculxivmtccj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqZ3hlZXhueWN1bHhpdm10Y2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NTQ0NTMsImV4cCI6MjA1NjIzMDQ1M30.IvNRBQ53vN7mCosyazwgAt_PSoQn-PMYDOu68J-LhEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);